version: '3.8'
# Logging config
x-logging:
  &logging
  driver: "local"
  options:
    max-size: "5m"
    max-file: "3"

services:
  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    logging: *logging
    volumes:
      - sqlite_data:/rails/storage

volumes:
  sqlite_data:
