production:
  work_dir: "/work_syn/ngs/analysis"
  illumina_dirs: ["/work_syn/ngs/runs"]
  pipeline_profile: "lsh"

development:
  work_dir: "/work_syn/ngs/analysis"
  illumina_dirs: ["/work_syn/ngs/runs"]
  pipeline_profile: "lsh"
